# Generated by Django 6.0 on 2025-12-17 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue'), ('LOST', 'Lost/Damaged')], default='ACTIVE', help_text='Current status of the loan', max_length=20)),
                ('borrowed_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when book was borrowed')),
                ('due_date', models.DateTimeField(help_text='Date and time when book should be returned')),
                ('returned_date', models.DateTimeField(blank=True, help_text='Date and time when book was actually returned', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the loan')),
                ('renewed_count', models.PositiveIntegerField(default=0, help_text='Number of times loan has been renewed')),
                ('max_renewals', models.PositiveIntegerField(default=2, help_text='Maximum number of renewals allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(help_text='Book that was borrowed', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library.book')),
                ('user', models.ForeignKey(help_text='User who borrowed the book', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-borrowed_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='loans_user_id_efac20_idx'), models.Index(fields=['book', 'status'], name='loans_book_id_6360b6_idx'), models.Index(fields=['due_date'], name='loans_due_dat_3e4b70_idx'), models.Index(fields=['status'], name='loans_status_9049a0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('renewed_count__lte', models.F('max_renewals'))), name='renewed_count_within_limit')],
            },
        ),
    ]
